trigger:
- "*"

pool:
  vmImage: ubuntu-latest

stages:

- stage: DEV

  jobs:

  - deployment: DeployDEV

    environment: DEV

    strategy:
      runOnce:
        deploy:
          steps:

          - script: |
              echo Deploying to DEV