trigger:
- "*"

pool:
  vmImage: ubuntu-latest

stages:

- stage: DEV

  jobs:

  - deployment: DeployDEV

    environment: DEV

    strategy:
      runOnce:
        deploy:
          steps:

          - script: |
              echo Deploying to DEV
- stage: UAT

  jobs:

  - deployment: DeployUAT

    environment: UAT

    strategy:
      runOnce:
        deploy:
          steps:

          - script: |
              echo Deploying to UAT
- stage: PROD

  jobs:

  - deployment: DeployPROD

    environment: PROD

    strategy:
      runOnce:
        deploy:
          steps:

          - script: |
              echo Deploying to PROD